name: Deploy Backend
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/web-app-kidsartcraft-backend
          git pull origin master

          cd ~/kids-art-craft-docker-compose
          docker-compose -p ubuntu build backend
          docker-compose -p ubuntu up -d --no-deps backend
